### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by Gnefil** [Gnefil/Blog#1]
# Tasks yet to do:
- [x]  Add deployment script
- [x] Fill new blog with old blog's content
- [ ] Check the validity of posts e.g.
  - [ ] GitHub Actions post, which should update the default workflow and storing secrets steps.
- [ ] Look for ways to switch between languages
- [ ] Add comment system
